### ISSUE TITLE
user profile: projects: fail to load

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#218]
![image](https://user-images.githubusercontent.com/9661732/53505168-556e6080-3a81-11e9-8829-625d12ed552b.png)

the pop up seems to appear even when listing them, and for some users it doesn't list them at all

**Comment by tnagorra** [comment]
Someone with the admin credentials added **a user** in the admin panel without specifying the email.
@thenav56 has fixed the issue.

**Comment by eoglethorpe** [comment]
ooo interesting. is this behavior fixed for if an admin adds a user without an email address?

**Comment by eoglethorpe** [comment]
i'm reopening as i wanna ensure that this is resolved incase of a future occurrence

**Comment by AdityaKhatri** [comment]
The high priority issue has already been solved.
So, instead of re-opening the issue.
We should create a new issue as they are totally different although related.

We've prevented this from happening to a certain level by limiting the admin level privileges of the different accounts that have access to the admin console.

**Comment by eoglethorpe** [comment]
@AdityaKhatri do we have this new issue?
