### ISSUE TITLE
project Libya Situation Analysis (OA) Export options

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#296]
Hello Guys! Not sure why in the project Libya in the report structure i have options that do not belong to the analysis framework:
![image](https://user-images.githubusercontent.com/15996586/54907762-958cfb80-4ee6-11e9-9731-799e7c2cd87f.png)

I have an option "Severity", but also "uncategorized". should they be here? let me know. patrice

**Comment by eoglethorpe** [comment]
just an initial guess but has the AF changed over time?

**Comment by patricechataigner** [comment]
Probably yes. the strange thing is the severity one. It s a conditional widget.

**Comment by eoglethorpe** [comment]
the current behavior is to show fields from all widgets. Is that not what's
happening?


On Mar 25, 2019, at 14:48, Patrice Chataigner <notifications@github.com>
wrote:

Probably yes. the strange thing is the severity one. It s a conditional
widget.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/the-deep/deeper/issues/296#issuecomment-476204796>, or mute
the thread

**Comment by eoglethorpe** [comment]
@patricechataigner

**Comment by patricechataigner** [comment]
Ok so lets assume that the severity widget show because its a conditional widget. Then why the reliability widget is not showing? Why is there no option available in the severity menu in the export? i m just trying to understand. lets check this on wednesday it will be easier. Also, the uncategorized option probably shouldnt be there, any idea where it is coming from?  or does it come when we save and entries was taken from the lead? i, e, it s an entry without taggs?

**Comment by eoglethorpe** [comment]
putting on agenda for tomorrow. uncategorized is when an entry is not tagged using a 1D or 2D framework.
