### ISSUE TITLE
ZD issue #17 [project panel]

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#374]
Please check it out and let me know

**Comment by AdityaKhatri** [comment]
Hey Ewan, in future, could you share the link for the issue as well.

**Comment by pprabesh** [comment]
Hours: 3

**Comment by AdityaKhatri** [comment]
@eoglethorpe , we've replied to the issue and are awaiting the issuer's reply.

**Comment by eoglethorpe** [comment]
@AdityaKhatri yes i will share the link in the future. could also get fancy integrate GH with ZD.

@pprabesh  how come this was 3 hours? 

https://deephelp.zendesk.com/agent/tickets/17

**Comment by thenav56** [comment]
@eoglethorpe For 3 hours.
* We had to poll for the client's response (since we don't get notification).
* We had to check codebase, sentry and papertrail to identify the problem.

In the future to reduce time, as you suggested we need to implement a better notification for if there are any follow-ups.

Thanks,

**Comment by eoglethorpe** [comment]
thanks and god bless you @thenav56
