### ISSUE TITLE
Edit Entries: NLP Recommendation missing for some leads

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#860]
NLP Recommendation are missing for some leads in edit entries page.

https://beta.thedeep.io/projects/1183/leads/18235/edit-entries/#/overview
https://beta.thedeep.io/projects/1183/leads/16964/edit-entries/#/overview

**Comment by bewakes** [comment]
@frozenhelium, @eoglethorpe the recommendations are missing because the lead simplified text has not been sent to DEEPL server(possibly the server being too busy, or the celery worker was killed). Currently, there is no auto re-triggering of this action, which will take some time.

For now, we can manually trigger the classification from shell for this particular project.

**Comment by bewakes** [comment]
@eoglethorpe also, it seems that DEEPL currently has problem processing/classifying very large texts(eg: from large pdfs) which cause the server to freeze for a while. We need to think of enhancing DEEPL as well.

**Comment by eoglethorpe** [comment]
thanks @bewakes; will take this to comms board to discuss further
