### ISSUE TITLE
Word export design feedback

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#953]

**Comment by eoglethorpe** [comment]
[20201006_DEEP_Entries_General_Export_Rw1FWAy.docx](https://zube.io/files/deep/999458608b501f31a7df46dac0de4103-20201006_deep_entries_general_export_rw1fway.docx)

**Comment by mariam-yu** [comment]
@eoglethorpe Some thoughts on the word doc legends. Hope addressing what you actually needed.

Challenge: Showing the legends on the top (unless the users are so used to that scale and what it represents, which I'm sure not all would, jus taggers) is not very useful since once you go through the document you have no clue what darkish blue is, and you can't just keep scrolling up to match the color and what it means.

Suggestion 1: If we want/need to keep the color scheme for the export, proposal to add a description next to eat and place below the excerpt. Even if it's repetitive, we can make it small, but just as a reference and it's clearer what it is.
![Screen Shot 2020-10-09 at 4.27.16 PM.png](https://zube.io/files/deep/ad978fbe9d0ce85774423eb0c3c2ee2d-screen-shot-2020-10-09-at-4-27-16-pm.png)

Suggestion 2: What would be even better is to specify what Severity is and what Reliability is and potentially replace the color with a different scale that is more explicit for the user, since they have a point of comparison, i.e. is it in the middle or hight, etc. Having one color is not very clear, so may be just a number system or other.

![Screen Shot 2020-10-09 at 4.27.31 PM.png](https://zube.io/files/deep/b0452c8b4ee00a9c8bf4b36eb0a3b543-screen-shot-2020-10-09-at-4-27-31-pm.png)

[DEEP_wordExample_MA.docx](https://zube.io/files/deep/9dfb3f646d2269e4c599418e89438376-deep_wordexample_ma.docx)

**Comment by AdityaKhatri** [comment]
@eoglethorpe , let us know what we should do.

**Comment by AdityaKhatri** [comment]
@Mariam-Asatryan , in suggestion one, we still keep the legend on the top right?

**Comment by mariam-yu** [comment]
@AdityaKhatri Yes, as there needs to be a reference to the color scheme.
